kind: pipeline
name: default
steps:
- name: generate-tags
  image: quay.io/natlibfi/drone-gen-tags
- name: test-init
  image: busybox
  commands:
  - chmod -R o+w /drone/src
- name: build
  image: node:10
  user: node
  commands:
  - npm install
  - npm test
- name: docker
  image: plugins/docker
  settings:
    repo: quay.io/natlibfi/melinda-merge
    registry: quay.io
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch: [master, test]
---
  kind: secret
  name: docker_username
  data: 6K/e4C/4TiXjvMc74YU5l3bQgF3mGFjXOO4uxmjBBymoSsaAjYGyoL7KXxH4jKF04Zs=
---
  kind: secret
  name: docker_password
  data: b88hKbU1r91ZQcnzIu53Kc3XgyrShCB9X5exzjh7Ndk8J0BO/ESsptVemHap18kgdY/X4OZBFqoZiuGDeAEQcKntsXL0ePYU5ZVh/GlbazkzOnTRypf0VczhpCQ=
...