language: node_js
node_js:
  - "4.5.0"
  - "node"
after_script:
  - if test "$TRAVIS_NODE_VERSION" != "4.5.0";then exit 0;fi
  - if test $TRAVIS_BRANCH = "master";then JOB=$JOB_PROD;elif test $TRAVIS_BRANCH = "test";then JOB=$JOB_TEST;elif test $TRAVIS_BRANCH = "fix-ci";then JOB=$JOB_TEST;fi
  - if test ! -z $JOB;then curl -X POST --data "authtoken=$AUTH_TOKEN&argString=-checkout-reference $TRAVIS_COMMIT" https://melinda-ci.lib.helsinki.fi/api/14/job/$JOB/executions;fi
env:
  global:
    - JOB_PROD=47200f32-c664-4906-841b-9e829d878fc0
    - JOB_TEST=25301283-47c1-4025-a40e-7c43b7f0a4d5
    - secure: "Rxk3ijfUBlLgwAG0Y3TLczg6XZx9Mdjpy0fn6ezqsHzCNtPvpo1f2NDhoqqd6rMTYbK6G77lXO2DaRYtls8x5nmBpO039HfztORTJd8XO7WK01G6NQ/9jCcogjt6FFiqlBCsKZsyiCdPYCOO67M0pys45GiYFWqthJrd5OkZ4kevMZB4hLNnQ9nbaEMswWkWpaVkZc7rZmIBbVzIN3yMBWU7xw/vgM+2+RSXnieG3ADgTqAQjw6jw1UsGGZD3OhnqQPFEFjVYTtD7drHrv3TJq2smXkrUGNsQmtMj1szuuov0hhst1pVIDbPbP3/r3WPB5S5kp8GCgd3/XEi/8PkRKp0sHAOLWVijDYaLzaHBWgC5reI9Sbx61gUFu35TQCw0iU2E7hymB4XlHqxoD+yKECh+n1fOXLZDu3lNMRHKXh0PMzNw5BPMg2cJzQEfl65YrJUgngZ/TI6cc50K2VATarpvoWh3fLIPHpngGwoKKHmcXDWG+iEq5VG9Q81XcsHBjnmGivsOtDRqOx33J3qia3SSWiazaGyZHuxn/jzvX5o8Pz/XPxbw/40PirI67oAaAmo8tIrekarwLmc+ciS5Tt9Ryg0KE2sJhG3PlYP9k2GC8MwbAyox2CT/b5t8t4sQK2nhTVs3plY++GqkR4UPsg7P/vF+M+p9KgK4IshsAc="
